#!/usr/bin/env bash
# Install + start the DUBO ROV Controller systemd service.
#
# Usage:  bash scripts/start.sh        (self-promotes to root via sudo)
#
# Discovers the real deployment path from this script's location (never
# guessed), then renders systemd/rov-controller.service into /etc/systemd/system,
# writes the GUI environment file, and enables + starts the service.
set -euo pipefail

# --- discover project root from our own location ------------------------------
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
UNIT_NAME="rov-controller.service"
UNIT_SRC="${PROJECT_ROOT}/systemd/${UNIT_NAME}"
UNIT_DST="/etc/systemd/system/${UNIT_NAME}"
ENV_FILE="/etc/rov-controller.env"

# --- self-promote to root (installing a system unit needs it) -----------------
if [[ ${EUID} -ne 0 ]]; then
    echo "Installing a systemd unit requires root — re-running with sudo..." >&2
    exec sudo -p "sudo password for %u: " bash "$0" "$@"
fi

echo "==> DUBO ROV Controller auto-start"
echo "    project root : ${PROJECT_ROOT}"

# --- discover the deployment user + venv python -------------------------------
ROV_USER="$(stat -c '%U' "${PROJECT_ROOT}")"
ROV_PYTHON="${PROJECT_ROOT}/.venv/bin/python"
[[ -n "${ROV_USER}" && "${ROV_USER}" != "UNKNOWN" ]] || {
    echo "ERROR: cannot determine the owner of ${PROJECT_ROOT}" >&2
    exit 1
}
getent passwd "${ROV_USER}" >/dev/null || {
    echo "ERROR: service user '${ROV_USER}' does not exist on this system" >&2
    exit 1
}
[[ -x "${ROV_PYTHON}" ]] || {
    echo "ERROR: venv python not found: ${ROV_PYTHON}" >&2
    echo "       Recreate it first, e.g.:" >&2
    echo "         python3 -m venv ${PROJECT_ROOT}/.venv" >&2
    echo "         ${PROJECT_ROOT}/.venv/bin/pip install opencv-python PySide6 pillow PyYAML numpy" >&2
    exit 1
}
echo "    service user : ${ROV_USER}"
echo "    python       : ${ROV_PYTHON}"

# --- GUI environment file (verified live values, not blind defaults) ----------
HOME_DIR="$(getent passwd "${ROV_USER}" | cut -d: -f6)"
DISPLAY_V=":0"
XAUTH_V="${HOME_DIR}/.Xauthority"
QT_PLAT_V="xcb"   # PySide6 over XWayland/X11 on Raspberry Pi OS

# Prefer the service user's actual graphical session if one exists.
if command -v loginctl >/dev/null 2>&1; then
    SID="$(loginctl --no-legend list-sessions 2>/dev/null | awk -v u="${ROV_USER}" '$3 == u {print $1; exit}')"
    if [[ -n "${SID}" ]]; then
        SESSION_DISPLAY="$(loginctl show-session "${SID}" -p Display --value 2>/dev/null || true)"
        [[ -n "${SESSION_DISPLAY}" ]] && DISPLAY_V="${SESSION_DISPLAY}"
    fi
fi
[[ -f "${XAUTH_V}" ]] || XAUTH_V="/home/${ROV_USER}/.Xauthority"

cat > "${ENV_FILE}" <<EOF
# Generated by ${PROJECT_ROOT}/scripts/start.sh on $(date -Is) for user ${ROV_USER}
# Qt needs a display; these are the values discovered for the live session.
DISPLAY=${DISPLAY_V}
XAUTHORITY=${XAUTH_V}
QT_QPA_PLATFORM=${QT_PLAT_V}
EOF
echo "    gui env      : ${ENV_FILE} (DISPLAY=${DISPLAY_V}, QT_QPA_PLATFORM=${QT_PLAT_V})"

# --- render the unit from the template with the discovered values -------------
if ! grep -Eq '@ROV_(USER|DIR|PYTHON)@' "${UNIT_SRC}"; then
    echo "ERROR: expected @ROV_*@ tokens in ${UNIT_SRC}" >&2
    exit 1
fi
sed -e "s|@ROV_USER@|${ROV_USER}|g" \
    -e "s|@ROV_DIR@|${PROJECT_ROOT}|g" \
    -e "s|@ROV_PYTHON@|${ROV_PYTHON}|g" \
    "${UNIT_SRC}" > "${UNIT_DST}"

if grep -Eq '@ROV_(USER|DIR|PYTHON)@' "${UNIT_DST}"; then
    echo "ERROR: unit rendering left unresolved tokens:" >&2
    grep -n '@ROV_' "${UNIT_DST}" >&2
    exit 1
fi
echo "    unit         : ${UNIT_DST}"

# --- enable + start ------------------------------------------------------------
systemctl daemon-reload
systemctl enable "${UNIT_NAME}"
systemctl restart "${UNIT_NAME}"

sleep 4
if ! systemctl is-active --quiet "${UNIT_NAME}"; then
    echo "ERROR: service did not become active. Recent journal:" >&2
    journalctl -u "${UNIT_NAME}" -n 30 --no-pager >&2 || true
    exit 1
fi

echo
echo "==> rov-controller is RUNNING"
echo "    status  : systemctl status ${UNIT_NAME}"
echo "    logs    : journalctl -u ${UNIT_NAME} -f"
systemctl status "${UNIT_NAME}" --no-pager -l || true